### ISSUE TITLE
cloudscrapper

### ISSUE THREAD

**Issue by rcalo** [MonkeyAndres/animeflv-scrapper#3]
Hola, estoy intentado utilizar tu módulo y me está dando error de CROS, esto es porque no estás en la última versión de cloudscrapper. 

Piensas actualizar esto y subir una nueva versión a npm? 

Está genial lo que estás haciendo y si se corrige eso seguro que voy hacer algo con este módulo.

espero tu respuesta

**Comment by MonkeyAndres** [comment]
Hola, gracias por abrir el issue, ya esta solucionado, prueba con la version 0.1.8 y me cuentas

**Comment by rcalo** [comment]
Hola, gracias por la respuesta. Lo he probado.

Si ejecuto tu código de ejemplo funciona, pero si lo hago utilizando create-react-app ya no me funciona.

me estoy perdiendo porque da el error, tendrás idea de por qué no me funciona?

esto es lo que tengo
`
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import API from 'animeflv-scrapper'

class App extends Component {
  render() {

    API.getAllAnimes().then( data => console.log(data))

    return (
      <div className="App">
        <header>Hola nuevo intento</header>  
      </div>
    );
  }
}

export default App;
`

El error que me da es el siguiente

![Captura](https://user-images.githubusercontent.com/49033351/56579649-194e0c80-65a7-11e9-980d-fdcbcb9dd5b9.PNG)

**Comment by mecm1993** [comment]
Hola @rcalo, 

El problemita que tienes es debido a que Chrome no soporta peticiones CORS desde el localhost. Para esto, puedes instalar la siguiente extension [Allow Control Allow Origin: *](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi), solo debes habilitarlo mientras estas desarrollando. 

Si deseas saber mas sobre CORS, te recomiendo el siguiente articulo [Practical Guide to CORS](https://medium.com/@xinganwang/a-practical-guide-to-cors-51e8fd329a1f). Espero que esto solucione tu problema.
