### ISSUE TITLE
Error al traer los ultimos episodios

### ISSUE THREAD

**Issue by wrtisans** [MonkeyAndres/animeflv-scrapper#4]
Hola, estoy tratando de traer los ultimos episodios, los del dia actual pero no logro hacer que funcione, estoy haciendo esto 

` const params = {
                                order: 'updated',
                                year: 2019, 
                                page: 1,
                        };`
                        `const apiRequest = API.getAnimes(params).then(data => data);`

he intentado sin el año, y en vez de updated added pero sigue igual. me los trae en un orden aleatorio. Gracias por tu ayuda.

**Comment by MonkeyAndres** [comment]
Hola tio, la funcion `getAnimes()` te trae los ultimos animes del listado de AnimeFLV, mas concretamente te dejo el link: https://animeflv.net/browse
No he implementado ningun metodo para traer los ultimos episodios publicados pero lo voy a apuntar para mas adelante, sientete libre de abrir pull request si quieres contibuir.
